import styles from './About.module.css';

export const metadata = {
    title: "About Us",
    description: "Generated by About Us next app",
  };

const page = () => {
    return (
        <div >
            <h1 className={styles.text_color}>about</h1>
        </div>
    );
};

export default page;